# ============================================================
# /etc/opendkim.conf — Configuración de OpenDKIM
# ============================================================

AutoRestart         yes
Syslog              yes
Canonicalization    relaxed/simple
SignatureAlgorithm  rsa-sha256
Mode                sv
Socket              inet:12301@localhost
UserID              opendkim:opendkim

KeyTable            refile:/etc/opendkim/KeyTable
SigningTable        refile:/etc/opendkim/SigningTable
InternalHosts       refile:/etc/opendkim/TrustedHosts
